### ISSUE TITLE
Cimkezes: ha a felhasznalo mar felvitt cimket probal egy kephez hozzaadni, a backend hibaval ter vissza (HTML status 500)

### ISSUE THREAD

**Issue by jepegrafik** [fortepan/fortepan.hu#20]
Az egyik lehetséges megoldás ha a frontenden lekérhető a képhez tartozó cimkék listája, és a backend felé küldött listából kiszűrjük ezeket.

Ehhez szükséges: https://github.com/fortepan/fortepan.hu/projects/2#card-51889526

**Comment by chx** [comment]
Hát egyszerűbb lenne ha megoldanánk hogy ne legyen hiba. Tudsz adni -- mondjuk `cURL` repro kódot? Küldtem be egy javítást, hogy használhatóbb választ addjon, van esetleg mintád hogy milyen hiba, milyen JSON válasz ha egyáltalán érkezik?

**Comment by jepegrafik** [comment]
> Hát egyszerűbb lenne ha megoldanánk hogy ne legyen hiba. Tudsz adni -- mondjuk `cURL` repro kódot? Küldtem be egy javítást, hogy használhatóbb választ addjon, van esetleg mintád hogy milyen hiba, milyen JSON válasz ha egyáltalán érkezik?

A frontend hívás most így néz ki:
`
  const url = "https://drupal.admin.fortepan.hu/fortepan/cimke"
  const resp = await fetch(url, {
    method: "POST",
    credentials: "include",
    headers: {
      "Content-Type": "application/json",
      Accept: "application/json",
    },
    body: JSON.stringify(data),
  })
`

Az elküldött adatok (data) egy konkrét esetben pedig így néz ki:
`{cimke: ["Budapest", "teszt"], image: 251003}`

Jelenleg a visszatérő válasz:
`A webhelyen nem várt hiba történt. Később érdemes újra megpróbálni.`

Reprodukálni úgy tudod, ha egy a képhez már felvett címkét elküldesz újra vagy egyedül vagy egyéb címkékkel együtt. A fenti esetben a képhez (id:251003) már hozzá van rendelve a "Budapest" címke, ezért jön vissza hibás válasz.

**Comment by chx** [comment]
Nézzd meg most.

**Comment by jepegrafik** [comment]
Nálam most jól működik, nem jön vissza hiba, a válaszban ennyit látok: `{count:0}`
Köszi a segítséget, zárom a ticketet.

**Comment by chx** [comment]
Az azt jelenti, hogy nulla címkét adott hozzá.

Ha sikerült volna, egyet írna. Ha több címkét küldsz, annak megfelelően.

**Comment by jepegrafik** [comment]
Értem, köszi. A fenti példában csak Budapestet vittem fel, ami már hozzá volt adva a képhez. 'Budapest' es 'teszt' címkék küldésénél a válasz helyesen `{count:1}`.
