### ISSUE TITLE
Rögzített, de adminisztátor által még nem elfogadott címkék megjelenítése belépett felhasználóknak

### ISSUE THREAD

**Issue by richardgazdik** [fortepan/fortepan.hu#5]
Felhasználói visszajelzések alapján szükség volna egy olyan felületre részletes nézetben, ahol a belépett felhasználó láthatná az adott képhez felvett, de még adminisztátor által el nem fogadott saját címkéket.

A címkék listázásához már elkészült az API hívás, ami ezen címkék listázásban segít (akár képre szűrve):
`/fortepan/cimke/list`  és `/fortepan/cimke/list?image=123456`  listázza a nem publikált címke-kép kapcsolatokat, igény szerint képre szűrve.
A visszaküldött válasz legfelső index a nyelvkód (hu, en), utána van a képek száma , utána a címkék listája.

**Comment by jepegrafik** [comment]
Backend fixre vár.

**Comment by chx** [comment]
Javítva
